openapi: 3.1.0
info:
  title: Flask REST-API
components:
  securitySchemes:
    Authorization-Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: JWT
  - name: User
paths:
  /jwt/:
    post:
      tags:
        - JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: taro@email.com
                password:
                  type: string
                  example: Taro1234
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: Json.Web.Token
  /user/:
    get:
      tags:
        - User
      security:
        - Authorization-Bearer: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: taro@email.com
                  name:
                    type: string
                    example: Taro
    post:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  example: taro@email.com
                password:
                  type: string
                  example: Taro1234
                name:
                  type: string
                  example: Taro
      responses:
        '204':
          description: No Content
    patch:
      tags:
        - User
      security:
        - Authorization-Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - current_password
              properties:
                current_password:
                  type: string
                  example: Taro1234
                email:
                  type: string
                  example: new-taro@email.com
                password:
                  type: string
                  example: NewTaro1234
                name:
                  type: string
                  example: New Taro
      responses:
        '204':
          description: No Content
    delete:
      tags:
        - User
      security:
        - Authorization-Bearer: []
      responses:
        '204':
          description: No Content
